version: "3.8"
services:
    nodeserver:
        container_name: nodeserver
        build:
            context: ./app
        tty: true
        networks: 
           - node-network
        depends_on: 
            db:
                condition: service_healthy
        volumes:
            - ./app:/usr/src/app
            - /usr/src/app/node_modules # volume anônimo para evitar a sobrescrita


    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:80"
        networks: 
            - node-network 
        depends_on:
            - nodeserver

    db:
        platform: linux/x86_64
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
          - ./mysql:/var/lib/mysql
        environment: 
          - MYSQL_DATABASE=nodedb
          - MYSQL_ROOT_PASSWORD=root
        networks: 
          - node-network
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

networks: 
    node-network:
        driver: bridge      