version: "3.8"
services:
    nodeserver:
        container_name: nodeserver
        build:
            context: ./app
        tty: true
        networks: 
           - node-network
        depends_on: 
            - db
        volumes:
            - ./app:/usr/src/app
        # ports:
        #     - "3000:3000"
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:80"
        networks: 
            - node-network   

    db:
        platform: linux/x86_64
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
          - ./mysql:/var/lib/mysql
        environment: 
          - MYSQL_DATABASE=nodedb
          - MYSQL_ROOT_PASSWORD=root
        networks: 
          - node-network

networks: 
    node-network:
        driver: bridge      